# Generated by Django 5.2.7 on 2025-10-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingrediente",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("frutas_verduras", "Frutas y verduras"),
                    ("carnes_pescados", "Carnes y pescados"),
                    ("panaderia", "Panadería"),
                    ("lacteos", "Lácteos"),
                    ("bebidas", "Bebidas"),
                    ("otros", "Otros"),
                ],
                default="otros",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="receta",
            name="categoria_nutricional",
            field=models.CharField(
                blank=True,
                choices=[
                    ("carbohidratos", "Carbohidratos"),
                    ("proteinas", "Proteínas"),
                    ("grasas", "Grasas"),
                    ("fibra", "Fibra"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
