# Generated by Django 5.2.7 on 2025-10-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0002_ingrediente_categoria_receta_categoria_nutricional"),
    ]

    operations = [
        migrations.AddField(
            model_name="hogar",
            name="comensales_default",
            field=models.PositiveIntegerField(
                default=2, help_text="Número habitual de comensales del hogar"
            ),
        ),
        migrations.AddField(
            model_name="plansemanal",
            name="comensales",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ingrediente",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("frutas_verduras", "Frutas y verduras"),
                    ("carnes_charcuteria", "Carnes y charcutería"),
                    ("pescados_marisco", "Pescados y marisco"),
                    ("aceites_especias_salsas", "Aceites, especias y salsas"),
                    ("arroz_legumbres_pasta", "Arroz, legumbres y pasta"),
                    ("dulces", "Dulces"),
                    ("snacks", "Snacks y frutos secos"),
                    ("panaderia", "Panadería"),
                    ("lacteos", "Lácteos"),
                    ("bebidas", "Bebidas"),
                    ("congelados", "Congelados"),
                    ("desayunos_cereales", "Desayunos y cereales"),
                    ("otros", "Otros"),
                ],
                default="otros",
                max_length=50,
            ),
        ),
    ]
