# Generated by Django 5.2.7 on 2025-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0003_hogar_comensales_default_plansemanal_comensales_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingrediente",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("frutas_verduras", "Frutas y verduras"),
                    ("carnes_charcuteria", "Carnes y charcutería"),
                    ("pescados_marisco", "Pescados y marisco"),
                    ("aceites_especias_salsas", "Aceites, especias y salsas"),
                    ("arroz_legumbres_pasta", "Arroz, legumbres y pasta"),
                    ("dulces", "Dulces"),
                    ("snacks", "Snacks y frutos secos"),
                    ("panaderia", "Panadería"),
                    ("lacteos", "Lácteos"),
                    ("bebidas", "Bebidas"),
                    ("congelados", "Congelados"),
                    ("desayunos_cereales", "Desayunos y cereales"),
                    ("conservas", "Conservas"),
                    ("otros", "Otros"),
                ],
                default="otros",
                max_length=50,
            ),
        ),
    ]
